// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
#include "strfuncs.h"
#include <stdlib.h>
#include <string.h>

// Exported Functions from `strfuncs:funcs/funcs`



// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void strfuncs_string_set(strfuncs_string_t *ret, const char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void strfuncs_string_dup(strfuncs_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void strfuncs_string_dup_n(strfuncs_string_t *ret, const char*s, size_t len) {
  ret->len = len;
  ret->ptr = (uint8_t*) cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void strfuncs_string_free(strfuncs_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

__attribute__((__export_name__("strfuncs:funcs/funcs#len")))
int32_t __wasm_export_exports_strfuncs_funcs_funcs_len(uint8_t * arg, size_t arg0) {
  strfuncs_string_t arg1 = (strfuncs_string_t) { (uint8_t*)(arg), (arg0) };
  uint32_t ret = exports_strfuncs_funcs_funcs_len(&arg1);
  return (int32_t) (ret);
}

__attribute__((__export_name__("strfuncs:funcs/funcs#print")))
void __wasm_export_exports_strfuncs_funcs_funcs_print(uint8_t * arg, size_t arg0) {
  strfuncs_string_t arg1 = (strfuncs_string_t) { (uint8_t*)(arg), (arg0) };
  exports_strfuncs_funcs_funcs_print(&arg1);
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_strfuncs(void);
__attribute__((used))
void __component_type_object_force_link_strfuncs_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_strfuncs();
}
