// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
#ifndef __BINDINGS_STRFUNCS_H
#define __BINDINGS_STRFUNCS_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct strfuncs_string_t {
  uint8_t*ptr;
  size_t len;
} strfuncs_string_t;

// Exported Functions from `strfuncs:funcs/funcs`
uint32_t exports_strfuncs_funcs_funcs_len(strfuncs_string_t *str);
void exports_strfuncs_funcs_funcs_print(strfuncs_string_t *str);

// Helper Functions

// Sets the string `ret` to reference the input string `s` without copying it
void strfuncs_string_set(strfuncs_string_t *ret, const char*s);

// Creates a copy of the input nul-terminated string `s` and
// stores it into the component model string `ret`.
void strfuncs_string_dup(strfuncs_string_t *ret, const char*s);

// Creates a copy of the input string `s` with length `len` and
// stores it into the component model string `ret`.
// The length is specified in code units (bytes for UTF-8, 16-bit values for UTF-16).
void strfuncs_string_dup_n(strfuncs_string_t *ret, const char*s, size_t len);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void strfuncs_string_free(strfuncs_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
